### ISSUE TITLE
API 20141201 returning incorrect error code

### ISSUE THREAD

**Issue by GameProgramer** [SchedulesDirect/JSON-Service#61] opened 2015-05-11 03:15 UTC
The /schedules end point returned a weird error today. I believe it should have returned 7000 (SCHEDULED_QUEUED) instead.

Here's the output from my grabber:

Getting listings for KQEHDT (KQEH-DT) [Channel 710]
Warning: Operation returned an error. Response: {
  "stationID": "44690",
  "code": 7100,
  "message": "The schedule you requested has been queued for generation but is not yet ready for download. Retry."
}
Error: Operation failed!

**Comment by rkulagowski** [comment] 2015-05-11 04:13
I will investigate and look for your error in the logs.

**Comment by GameProgramer** [comment] 2015-06-08 14:33
Any news on this? This is still happening. I got the same error as of this morning:

Getting listings for National Geographic Channel HD (Pacific) [Channel 757]
Warning: Operation returned an error. Response: {
  "stationID": "71601",
  "code": 7100,
  "message": "The schedule you requested has been queued for generation but is not yet ready for download. Retry."
}

**Comment by rkulagowski** [comment] 2015-06-08 17:57
Are you still having this issue?

7000 is returned if you've submitted a stationID that doesn't exist. 7100 is returned if you've submitted a valid stationID, but which we don't have data for when you sent the request. (There are various reasons for this, including if you're the first person to request a stationID, in which case the batch process hasn't generated the schedule and it's being created just-in-time, or if there's a bug in my code).

So 7100 was the proper response in this case. The issue was on my side; the process that generates the just-in-time schedule had an error, which should be fixed.

**Comment by GameProgramer** [comment] 2015-06-08 19:30
Ah, the error numbers have been changed. In the previous API it was the other way around. 7000 was schedule queued and 7100 was schedule not found. 

I don't believe this change was documented in the thread that tracked these changes: (http://forums.schedulesdirect.org/viewtopic.php?f=17&t=2645).

I can fix this on my end, but humbly request that you keep existing clients in mind before making non-backward compatible changes.

Thanks.

**Comment by rkulagowski** [comment] 2015-06-08 19:35
It was a divergence in the documentation and what the code had internally, and that's my fault; the responses for programID was one way, and schedules was the other way, and when code was refactored it caused a change in the output pattern. That won't happen again.

20150501 is going to have a redesign of the error responses because there's too much cruft that accumulated from old APIs that is no longer relevant, but that's for the future.

**Comment by GameProgramer** [comment] 2015-06-08 19:45
I understand, these things happen.

Given that 20150501 seems like its going to have a lot of breaking changes, my biggest question is at what time do you expect to have a stable API? I ask, because the current API satisfies all of my needs and I really have no desire to upgrade to a newer version and only do so because of the retirement policy.

Thanks.

**Comment by rkulagowski** [comment] 2015-06-23 14:41
There was a lot of backend code on 20140530 that just wasn't going to be scaleable. The backend for 20141201 makes it easier to maintain different "views" all based on a common backend data. 20141201 will be stable for a while so it won't need to be retired as quickly as 2013XXXX or 20140530.

**Comment by rkulagowski** [comment] 2015-06-23 14:44
Also, the root cause of this particular issue was an error on my side; it's been fixed (sanity checking the dates that are submitted, returning an error if a date is out of the range of data that we have on the server), so I will close this ticket. We can move the discussion of the API-20150501 to the thread on the Developer forum.

http://forums.schedulesdirect.org/viewtopic.php?f=17&t=2678

**Closed by rkulagowski** 2015-06-23 14:44 UTC
