### ISSUE TITLE
int stationID with /schedules

### ISSUE THREAD

**Issue by brunoqc** [SchedulesDirect/JSON-Service#64] opened 2015-06-04 01:16 UTC
Most stationID are strings but I got one int.

```json
  {
    "stationID": 89876,
    "programs": [
      {}
    ]
  }
```

**Comment by rkulagowski** [comment] 2015-06-04 13:34
Very odd. Which API is this?

I just pulled API20141201 and I've got this:

{"stationID":"89876","programs":[{"programID":"SH019649920000","airDateTime":"2015-06-04T00:00:00Z","duration":14400,"md5":"N6f\/\/dbakgFclzLSSXHwQQ"},{"programID":"SH019649920000","airDateTime":"2015-06-04T04:00:00Z","duration":14400,"md5":"N6f\/\/dbakgFclzLSSXHwQQ"},{"programID":"SH019649920000","airDateTime":"2015-06-04T08:00:00Z","duration":14400,"md5":"N6f\/\/dbakgFclzLSSXHwQQ"},{"programID":"SH019649920000","airDateTime":"2015-06-04T12:00:00Z","duration":14400,"md5":"N6f\/\/dbakgFclzLSSXHwQQ"},{"programID":"SH019649920000","airDateTime":"2015-06-04T16:00:00Z","duration":14400,"md5":"N6f\/\/dbakgFclzLSSXHwQQ"},{"programID":"SH019649920000","airDateTime":"2015-06-04T20:00:00Z","duration":14400,"md5":"N6f\/\/dbakgFclzLSSXHwQQ"}],"metadata":{"modified":"2015-06-04T13:22:07Z","md5":"wy73M05vFLgcTq7TWyOhjA","startDate":"2015-06-04"}}

Can you let me know what you're doing so that I can try to duplicate it here?

**Comment by brunoqc** [comment] 2015-06-10 00:23
I don't have the problem anymore. Maybe it was with 2015-06-03.

**Comment by rkulagowski** [comment] 2015-06-23 14:34
Couldn't reproduce, closing ticket.

**Closed by rkulagowski** 2015-06-23 14:34 UTC
